"""SMTP mail helpers for Phase 1E notification triggers."""

from __future__ import annotations

import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Optional


def _get_smtp_cfg() -> dict:
    return {
        "host": os.environ["SMTP_HOST"],
        "port": int(os.environ.get("SMTP_PORT", "587")),
        "user": os.environ["SMTP_USER"],
        "password": os.environ["SMTP_PASSWORD"],
    }


def build_churn_email_body(
    vendor: str,
    department: Optional[str],
    candidates: list[dict],
    dollar_impact: float,
) -> str:
    dept_label = f" / {department}" if department else ""
    rows = "".join(
        "<tr>"
        f"<td>{c.get('license_id', '')}</td>"
        f"<td>{c.get('employee', c.get('email', ''))}</td>"
        f"<td>{c.get('department', '')}</td>"
        f"<td>{c.get('last_login', c.get('days_since_last_active', ''))}</td>"
        f"<td>${float(c.get('annual_value', c.get('annual_cost', 0)) or 0):,.0f}</td>"
        "</tr>"
        for c in candidates
    )
    return f"""
<h2>[SaaS Spend] Churn Notification - {vendor}{dept_label}</h2>
<p>The following {len(candidates)} licenses have been identified as inactive.
Total recoverable annual value: ${dollar_impact:,.0f}.</p>
<table border="1" cellpadding="6" cellspacing="0">
  <thead>
    <tr>
      <th>License ID</th><th>Employee</th><th>Department</th>
      <th>Last Login</th><th>Annual Value</th>
    </tr>
  </thead>
  <tbody>{rows}</tbody>
</table>
<p>Generated by SaaS Spend Management Platform - Phase 1E</p>
""".strip()


def send_churn_notification(
    vendor: str,
    department: Optional[str],
    candidates: list[dict],
    dollar_impact: float,
    preview_only: bool = True,
) -> dict:
    """
    Preview or send a churn notification email.

    SMTP exceptions intentionally propagate to callers so routers/tools can
    return their own structured error shape.
    """

    recipient = os.environ["CHURN_NOTIFICATION_RECIPIENT"]
    dept_label = f" / {department}" if department else ""
    subject = f"[SaaS Spend] Churn notification - {vendor}{dept_label}"
    body_html = build_churn_email_body(vendor, department, candidates, dollar_impact)

    if preview_only:
        return {
            "preview": True,
            "recipient": recipient,
            "subject": subject,
            "body_preview": body_html[:400] + ("..." if len(body_html) > 400 else ""),
            "candidate_count": len(candidates),
            "dollar_impact": dollar_impact,
        }

    cfg = _get_smtp_cfg()
    msg = MIMEMultipart("alternative")
    msg["From"] = cfg["user"]
    msg["To"] = recipient
    msg["Subject"] = subject
    msg.attach(MIMEText(body_html, "html"))

    with smtplib.SMTP(cfg["host"], cfg["port"]) as server:
        server.ehlo()
        server.starttls()
        server.login(cfg["user"], cfg["password"])
        server.sendmail(cfg["user"], recipient, msg.as_string())

    return {
        "preview": False,
        "sent": True,
        "recipient": recipient,
        "subject": subject,
        "candidate_count": len(candidates),
        "dollar_impact": dollar_impact,
    }
