"""SMTP mail helpers for Phase 1E notification triggers."""

from __future__ import annotations

import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Optional


def _get_smtp_cfg() -> dict:
    return {
        "host": os.environ["SMTP_HOST"],
        "port": int(os.environ.get("SMTP_PORT", "587")),
        "user": os.environ["SMTP_USER"],
        "password": os.environ["SMTP_PASSWORD"],
    }


def build_churn_email_body(
    vendor: str,
    department: Optional[str],
    candidates: list[dict],
    dollar_impact: float,
) -> str:
    dept_label = f" / {department}" if department else ""
    rows = "".join(
        "<tr>"
        f"<td>{c.get('license_id', '')}</td>"
        f"<td>{c.get('employee', c.get('email', ''))}</td>"
        f"<td>{c.get('department', '')}</td>"
        f"<td>{c.get('last_login', c.get('days_since_last_active', ''))}</td>"
        f"<td>${float(c.get('annual_value', c.get('annual_cost', 0)) or 0):,.0f}</td>"
        "</tr>"
        for c in candidates
    )
    return f"""
<h2>[SaaS Spend] Churn Notification - {vendor}{dept_label}</h2>
<p>The following {len(candidates)} licenses have been identified as inactive.
Total recoverable annual value: ${dollar_impact:,.0f}.</p>
<table border="1" cellpadding="6" cellspacing="0">
  <thead>
    <tr>
      <th>License ID</th><th>Employee</th><th>Department</th>
      <th>Last Login</th><th>Annual Value</th>
    </tr>
  </thead>
  <tbody>{rows}</tbody>
</table>
<p>Generated by SaaS Spend Management Platform - Phase 1E</p>
""".strip()


def send_churn_notification(
    vendor: str,
    department: Optional[str],
    candidates: list[dict],
    dollar_impact: float,
    preview_only: bool = True,
) -> dict:
    """
    Preview or send a churn notification email.

    SMTP exceptions intentionally propagate to callers so routers/tools can
    return their own structured error shape.
    """

    recipient = os.environ["CHURN_NOTIFICATION_RECIPIENT"]
    dept_label = f" / {department}" if department else ""
    subject = f"[SaaS Spend] Churn notification - {vendor}{dept_label}"
    body_html = build_churn_email_body(vendor, department, candidates, dollar_impact)

    if preview_only:
        return {
            "preview": True,
            "recipient": recipient,
            "subject": subject,
            "body_preview": body_html[:400] + ("..." if len(body_html) > 400 else ""),
            "candidate_count": len(candidates),
            "dollar_impact": dollar_impact,
        }

    cfg = _get_smtp_cfg()
    msg = MIMEMultipart("alternative")
    msg["From"] = cfg["user"]
    msg["To"] = recipient
    msg["Subject"] = subject
    msg.attach(MIMEText(body_html, "html"))

    with smtplib.SMTP(cfg["host"], cfg["port"]) as server:
        server.ehlo()
        server.starttls()
        server.login(cfg["user"], cfg["password"])
        server.sendmail(cfg["user"], recipient, msg.as_string())

    return {
        "preview": False,
        "sent": True,
        "recipient": recipient,
        "subject": subject,
        "candidate_count": len(candidates),
        "dollar_impact": dollar_impact,
    }


def build_planning_brief_email_body(briefing: dict) -> str:
    s = briefing["portfolio_summary"]
    vendors = briefing.get("vendor_signals", [])
    tools = briefing.get("available_tools", [])

    def fmt_k(n): return f"${float(n or 0) / 1000:.0f}K"
    def fmt_pct(n): return f"{float(n or 0) * 100:.1f}%"

    vendor_rows = "".join(
        f"<tr>"
        f"<td>{v['vendor']}</td>"
        f"<td>{v['ghost_licenses']}</td>"
        f"<td>{fmt_k(v['ghost_waste_annual'])}/yr</td>"
        f"<td>{fmt_k(v['trueup_exposure'])}</td>"
        f"<td>{fmt_pct(v['utilization_rate'])}</td>"
        f"<td>{v['expired_contracts']}</td>"
        f"</tr>"
        for v in vendors
    )

    tool_rows = "".join(f"<li><code>{t}</code></li>" for t in tools)

    return f"""
<h2>[SaaS Spend] Planning Agent Briefing — {briefing.get('audit_date', '')}</h2>
<p>Generated at: {briefing.get('generated_at', '')}</p>

<h3>Portfolio Summary</h3>
<table border="1" cellpadding="6" cellspacing="0">
  <tr><th>Metric</th><th>Value</th></tr>
  <tr><td>Ghost Waste (Annual)</td><td>{fmt_k(s['ghost_waste_annual'])}/yr</td></tr>
  <tr><td>True-Up Exposure</td><td>{fmt_k(s['trueup_exposure'])}</td></tr>
  <tr><td>Avg Utilization</td><td>{fmt_pct(s['avg_utilization'])}</td></tr>
  <tr><td>Expired Contracts</td><td>{s['expired_contracts']}</td></tr>
</table>

<h3>Vendor Signals</h3>
<table border="1" cellpadding="6" cellspacing="0">
  <thead>
    <tr>
      <th>Vendor</th><th>Ghost Licenses</th><th>Ghost Waste</th>
      <th>True-Up Exposure</th><th>Utilization</th><th>Expired Contracts</th>
    </tr>
  </thead>
  <tbody>{vendor_rows}</tbody>
</table>

<h3>Available MCP Tools</h3>
<ul>{tool_rows}</ul>

<p>Generated by SaaS Spend Management Platform — Planning Agent Handoff</p>
""".strip()


def send_planning_brief(briefing: dict, preview_only: bool = True) -> dict:
    recipient = os.environ["CHURN_NOTIFICATION_RECIPIENT"]
    subject = f"[SaaS Spend] Planning Agent Briefing — {briefing.get('audit_date', '')}"
    body_html = build_planning_brief_email_body(briefing)

    if preview_only:
        return {
            "preview": True,
            "recipient": recipient,
            "subject": subject,
            "body_preview": body_html[:400] + ("..." if len(body_html) > 400 else ""),
        }

    cfg = _get_smtp_cfg()
    msg = MIMEMultipart("alternative")
    msg["From"] = cfg["user"]
    msg["To"] = recipient
    msg["Subject"] = subject
    msg.attach(MIMEText(body_html, "html"))

    with smtplib.SMTP(cfg["host"], cfg["port"]) as server:
        server.ehlo()
        server.starttls()
        server.login(cfg["user"], cfg["password"])
        server.sendmail(cfg["user"], recipient, msg.as_string())

    return {
        "preview": False,
        "sent": True,
        "recipient": recipient,
        "subject": subject,
    }